# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Documents/School/ECEN 397/FGPA_video_game/VGA/VGA.srcs/sources_1/ip/clock_25MHz/clock_25MHz.xci
# IP: The module: 'clock_25MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Documents/School/ECEN 397/FGPA_video_game/VGA/VGA.srcs/sources_1/ip/clock_25MHz/clock_25MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_25MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Documents/School/ECEN 397/FGPA_video_game/VGA/VGA.srcs/sources_1/ip/clock_25MHz/clock_25MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Documents/School/ECEN 397/FGPA_video_game/VGA/VGA.srcs/sources_1/ip/clock_25MHz/clock_25MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/Documents/School/ECEN 397/FGPA_video_game/VGA/VGA.srcs/sources_1/ip/clock_25MHz/clock_25MHz.xci
# IP: The module: 'clock_25MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Documents/School/ECEN 397/FGPA_video_game/VGA/VGA.srcs/sources_1/ip/clock_25MHz/clock_25MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Documents/School/ECEN 397/FGPA_video_game/VGA/VGA.srcs/sources_1/ip/clock_25MHz/clock_25MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Documents/School/ECEN 397/FGPA_video_game/VGA/VGA.srcs/sources_1/ip/clock_25MHz/clock_25MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
