# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Documents/School/ECEN 397/FGPA_video_game/VGA/VGA.srcs/sources_1/ip/vga_pll/vga_pll.xci
# IP: The module: 'vga_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Documents/School/ECEN 397/FGPA_video_game/VGA/VGA.srcs/sources_1/ip/vga_pll/vga_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Documents/School/ECEN 397/FGPA_video_game/VGA/VGA.srcs/sources_1/ip/vga_pll/vga_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Documents/School/ECEN 397/FGPA_video_game/VGA/VGA.srcs/sources_1/ip/vga_pll/vga_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/Documents/School/ECEN 397/FGPA_video_game/VGA/VGA.srcs/sources_1/ip/vga_pll/vga_pll.xci
# IP: The module: 'vga_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Documents/School/ECEN 397/FGPA_video_game/VGA/VGA.srcs/sources_1/ip/vga_pll/vga_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Documents/School/ECEN 397/FGPA_video_game/VGA/VGA.srcs/sources_1/ip/vga_pll/vga_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Documents/School/ECEN 397/FGPA_video_game/VGA/VGA.srcs/sources_1/ip/vga_pll/vga_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
